[project]
name = "malaga-agenda-web-scrapper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.13.4",
    "requests==2.32.3",
    "selenium==4.31.0",
]
